[project]
name = "odoo-addons-oca-account-invoice-reporting"
version = "18.0.20260526.0"
dependencies = [
    "odoo-addon-account_comment_template==18.0.*",
    "odoo-addon-account_invoice_line_report==18.0.*",
    "odoo-addon-account_invoice_line_sale_line_position==18.0.*",
    "odoo-addon-account_invoice_payment_mode_note_template==18.0.*",
    "odoo-addon-account_invoice_production_lot==18.0.*",
    "odoo-addon-account_invoice_report_grouped_by_picking==18.0.*",
    "odoo-addon-account_invoice_report_grouped_by_picking_sale_mrp==18.0.*",
    "odoo-addon-account_invoice_report_payment_info==18.0.*",
    "odoo-addon-account_invoice_report_picking_customer_note==18.0.*",
    "odoo-addon-account_invoice_report_product_sticker==18.0.*",
    "odoo-addon-account_invoice_report_salesperson==18.0.*",
    "odoo-addon-account_invoice_report_stock_packaging==18.0.*",
    "odoo-addon-account_reporting_volume==18.0.*",
    "odoo-addon-account_reporting_weight==18.0.*",
    "odoo-addon-partner_time_to_pay==18.0.*",
    "odoo-addon-stock_account_invoice_report_lot_expiry==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
